[project]
name = "veripy"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.3",
    "xdsl==0.63.0",
]

[tool.uv]
dev-dependencies = ["lit==18.1.8", "filecheck==1.0.3", "pyright==1.1.409"]

[project.scripts]
veripy = "veripy.main:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
namespaces = true

[tool.pyright]
enableExperimentalFeatures = true
enableTypeIgnoreComments = false
reportAssertAlwaysTrue = true
reportImportCycles = false
reportMissingModuleSource = false
reportUnnecessaryCast = true
reportUnnecessaryIsInstance = true
reportUnnecessaryTypeIgnoreComment = true
typeCheckingMode = "strict"
include = ["veripy"]
